# Generated by Django 4.2.7 on 2024-02-12 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Banking_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_account',
        ),
        migrations.AddField(
            model_name='customer',
            name='account_ptr',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Banking_App.account'),
        ),
    ]
